name: Patch Tuesday

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Patch Tuesday script
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            python patchtuesday.py "$(date +'%Y-%b')" --force
          else
            python patchtuesday.py "$(date +'%Y-%b')"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "Update Patch Tuesday report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
